### ISSUE TITLE
JWT の exp を Shibboleth SP のセッションの有効期限に合わせたい

### ISSUE THREAD

**Issue by mit0223** [procube-open/jwt-nginx-lua#2]
某プロジェクトで以下の手順で障害が発生しています。JWT の exp は生成後８時間に設定されています。
1. 4:00 にログイン→JWTのexp は 13:00 で Cookie に設定される & JavaScript の変数に保存される
2. 別のタブで 12:00 にログイン→JWTのexp は 21:00 で Cookie に設定される & JavaScript の変数に保存される
3. 14:00 に 1. のタブから API 呼び出しを実行
4. API呼び出し前に JavaScript で JWTの期限切れをチェックするも、2. で Cookie に入っている値をチェックし、期限切れで無いと判断
5. APIを呼び出すが、1, で JavaScript の変数に保存された古い JWT でアクセスし、期限切れのため、 JWT Issuer にリダイレクト
6. Shibboleth SP のセッションが切れているので、 IdP にリダイレクト
7. CORS により失敗
8. リロードすると、2. で設定された Cookie が有効なため、ログイン画面に行かずにアプリケーションが正常に表示される

問題を修正する方法は多数考えられるが、2. で  JWT を発行する際に  Shibboleth のセッションの有効期限に合わせることで、問題を解消することができると思われる。

**Comment by bluemurder14** [comment]
念のためですが、次のような状況と想定します。

- JWTの有効期間 exp 、Shibboleth SPの無通信タイムアウトおよびセッション有効期間いずれも同じ値（８時間）に設定されている
- 1も2もJWT発行要求であるが、1はSAML認証を伴うが（IdPで認証を実行）、2は認証済みアクセス（Shibboleth SPのセッション有効内）である

本JWT発行機能は、なんらかの認証（大抵の場合、Shibboleth SPのSAML認証を想定・推奨していますが）を通過したリクエストについて、JWTを発行するものです。
異なるJWTを発行しておきながら、なぜ区別しないのだろう、とは思いますが、機能追加で対応したいと思います。

Shibboleth SPとの連携の場合、以下２つの値を受け取ることが可能です。

- Shib-Session-Expires：セッション有効期限（Epoch time）
- Shib-Session-Inactivity：無通信タイムアウトの期限（Epoch time）

このうち、Shib-Session-Expires を JWT の exp にセットする機能を追加実装して対応で検討を進めます。

**Comment by mit0223** [comment]
はい、想定している状況で間違いありません。

> 異なるJWTを発行しておきながら、なぜ区別しないのだろう

これはプログラムの実装の都合で JWT の exp のチェックをするときは  Cookie に保存されているものを見ているが、いざ、APIを呼び出すときは JavaScript の変数に保存されている値を Authorization ヘッダーにつめるので、複数のタブを開いている場合、前者は共通、後者は個別となっています。
プログラムの実装も治したほうがいいのですが、とりあえず、これを入れていただければオールマイティに効くのでこちらを治したいです。今 JWT Verifyでは Query, Cookie, Authorization ヘッダーに複数ついている場合に優先度の低いほうが無視する仕様になっていますので、 JWT の exp は何度発行しても同じというのにしたいです。実際、今回の場合 Cookie の値は有効期限が切れていないのですが、 Authorization ヘッダーの値が優先されてリダイレクトされてます。

> Shib-Session-Inactivity を JWT の exp にセットする機能を追加実装して対応で検討を進めます。

はい、それでお願いします。互換性の問題もあるし、 Shibboleth との連携でなくても動作するようにしたいので、オプションにしてください。

**Comment by bluemurder14** [comment]
申し訳ありません。
大事なところの説明が誤っていたので修正しました（無通信タイムアウトとセッション有効期限の説明が逆）。
https://github.com/procube-open/jwt-nginx-lua/issues/2#issuecomment-1380215797

**Comment by bluemurder14** [comment]
「Shibboleth SPとの連携」に依存せず動的な値（HTTPヘッダや nginx variable）を設定できるような仕様で考えました。

- 既存の expSec 等の属性については全て変更なし
- 有効期限として expSecExt を設定できる
- expSecExt は、from と var_name を持ち、from には header や variable を指定できる
- expSecExt が指定されている場合、from と var_name の値に応じて有効期限の値を取得する（header の Shib-Session-Expires から取得する、など）
- 上記の値が数値でなければ、expSec を有効期限の値とする

設定JSONの例は以下の通り（該当部分のみ抜粋）。
```
        "encode": {
                "alg": "HS256",
                "key": "secret",
                "expSec": "120",
                "expSecExt": {
                        "from": "header",
                        "var_name": "Shib-Session-Expires"
                }
        },
```

**Comment by bluemurder14** [comment]
1.0.9 で修正しました。
